### PR TITLE
I've created a snap for OctoPrint

### PR DESCRIPTION
**Pull request by kz6fittycent**
* [ ] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch, or maintenance if it's
    a bug fix for an issue present in the current stable version (no PRs
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR 
    if necessary!
  * [x] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
To summarize, it provides a single package and package management system that allows all the needed libs, deps and whatever else to be included in a single, confined package. It's self-updating and more secure than other methods of installation. It's super user-friendly to boot. 

#### How was it tested? How can it be tested by the reviewer?
Limited testing. To install and test it: `sudo snap install --edge octoprint` from a Linux distro capable of running snaps (e.g. Ubuntu, Solus, Fedora, Gentoo, Arch, openSUSE)

#### Any background context you want to provide?
I like making snaps...

#### What are the relevant tickets if any?
n/a

#### Screenshots (if appropriate)
image

#### Further notes

I've created a "working" snap for OctoPrint but testers have been limited. I am submitting this PR for inclusion as it would provide an easier path for deployment to Linux distros running `snapd`. 

I often get the response: "I'm not familiar with snaps"

To summarize, it provides a single package and package management system that allows all the needed libs, deps and whatever else to be included in a single, confined package. It's self-updating and more secure than other methods of installation. It's super user-friendly to boot. 

I'd love to help out the project with this snap and welcome any questions you have. 

Regards

### CODE REVIEW

**Comment by foosel** [comment]
@kz6fittycent Hi! Thank you for this! Just like with [Docker support](https://github.com/foosel/OctoPrint/pull/1639) I'd prefer to keep things like this in their own repository, ideally maintained by people comfortable with the technology in question. If I merge this into OctoPrint core and someone down the line starts asking questions about it, I'll have to be able to answer. Same goes if it needs adjustment due to code changes. And truth be told I don't have the resources to now become familiar with snap enough to be able to maintain this :)

How about this - I provide you a repository under the OctoPrint Github organization and you maintain the snap file there? Or am I missing something crucial here in how this stuff is working?

As a side note, your snap file also still appears to be referring to your fork instead of the official one.

**Comment by kz6fittycent** [comment]
Hi @foosel , 

That sounds great. I'd be happy to provide any support I can to OctoPrint. As for the snap referring to my fork, that's pretty typical (of me) to do until I get a fully working snap. Once things are good, and I get in touch with "upstream" (i.e. you), I switch to the official one. 

Thanks for letting me contribute in this small way.

**Comment by foosel** [comment]
I've sent you an invite for https://github.com/OctoPrint/snap.

**Comment by kz6fittycent** [comment]
Thanks for this.

I'm kind of a noob at GitHub....so do I fork this to my repo and then
perform a PR?

TIA.

*James Tigert*

*"I am not bound to win, but I am bound to be true. I am not bound to
succeed,but I am bound to live by the light that I have. I must stand with
anybody that stands right, and stand with him while he is right, and part
with him when he goes wrong." -Abraham Lincoln*

**Comment by foosel** [comment]
@kz6fittycent you create a new folder somewhere on your PC, put your snap files + ideally a README there, define the new repo as upstream repository of that (how to do that should be explained on the repository itself as its empty right now) and then push.

Alternatively I can also take care of initializing stuff for you a bit more, just give me a ping if so.

Also sorry for the delay here, too many balls in the air again.

**Comment by foosel** [comment]
Hey, are you still looking into this?

**Comment by kz6fittycent** [comment]
TBH, I've placed it on the back burner for some time now. I'll close this and return with something at a later date.

**Comment by foosel** [comment]
Thank you for the quick solution!

As I pointed out above, I don't feel comfortable merging this as I have absolutely no knowledge of how snap works and I'd have to maintain it down the road if I put it on the official repo. I'd really prefer a separate repository that pulls in current sources maintained by someone who understands things and has time to properly maintain them. So I'll probably not merge this :/

**Pull request closed without merging**
