### PR TITLE
[WIP] Add system usage API endpoint

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
This is a work in progress.

Adds an API endpoint for querying folder usage. Needed for #1030

Replaces #2891

### CODE REVIEW

**Comment by HarlemSquirrel** [comment]
I'm still having trouble setting up the test session properly. This endpoint requires an API key and valid session cookie.

**Comment by foosel** [comment]
I'd honestly not test the endpoint through flask but rather test the underlying function directly. That way you can get rid of a ton of mocking and also don't run into the apikey issues you are having.

Your goal isn't to test that the flask routing works properly for the endpoint but rather that the endpoint returns the expected data for a mocked environment.

**Comment by HarlemSquirrel** [comment]
OK, I've simplified the tests a bit but am running into `AttributeError: 'Flask' object has no attribute 'login_manager'`. Maybe I need to mock `flask_login`?

**Comment by foosel** [comment]
My bad. I forgot that decorators replace the decorated function completely, so you still can't test it without the need of a flask context. Which is ... certainly going down a rabbit's hole that is way beyond what this test should be about. I pushed a commit with a small refactoring that makes stuff easier testable, and also fixes the test while at it. Please take a look and tell me if that looks ok for you.

**Comment by HarlemSquirrel** [comment]
Ah, this is slick! I like it. :slightly_smiling_face:

**Comment by foosel** [comment]
Great! So, do you want to still add something to this specific PR or is it mergeable?

**Comment by HarlemSquirrel** [comment]
I think this works and is mergeable if you are happy.

**Pull request merged**
