### PR TITLE
Dev/hook upload sd card

### PR DESCRIPTION
**Pull request by devildant**
Hello,

I created and tested this hook to configure the module I designed, to replace the SD copy system (SD printer) by a much more powerful method.
I reach speeds ranging from 25 to 50 MB / s.
so hook allows the creation of the octoprint plugin to replace the sd download.
I mentioned the topic in this issue: #2798
during my test I managed a copy of a gcode of 100mo in 14s

### CODE REVIEW

**Comment by foosel** [comment]
So as it looks like you are still heavily working on that - could you give me a ping when you thing this is ready? I'd prefer to only have to review it once ;)

**Comment by devildant** [comment]
Hello,

yes I made a lot of changes in recent days, I develop at the same time my plugin that will use the hook.
it allows me to be sure to have something functional.
and yesterday I finished my 90% plugin. and it works perfectly.
you can watch. :)
I tried to do my best

**Comment by devildant** [comment]
I Confirm again it's OK, you can check :)

**Comment by devildant** [comment]
Hello, 
I send you a "ping" so that you do not forget me :)
I am well aware that your schedule needs to be loaded

**Comment by foosel** [comment]
@devildant thanks for the reminder ;) Haven't forgotten, just currently focused on the RCs for 1.3.10. I'll try to get around to this ASAP.

**Comment by devildant** [comment]
@foosel i saw the RCs notifications :)
I had a little hope that my hook would be accessible with octoprint 1.3.10 :)
courage for RCs

**Comment by devildant** [comment]
a new pull request has been created on the maintenance branch (https://github.com/foosel/OctoPrint/pull/2900) to avoid the cherry pick.
we can close this one if you want

**Comment by foosel** [comment]
Roger

**Pull request closed without merging**
