### PR TITLE
Patch3

### PR DESCRIPTION
**Pull request by Salandora**
Some small patches

Patched Context Menu,
Added showConfirmationDialog fucntion,
Fixed Control Layout,
Added OnSettingsBeforeSave function
Containers in Control tab are optionally collapsable (accordion way with a nice caret)

### CODE REVIEW

**Comment by foosel** [comment]
Hm, something's not right on my end. Checked out your branch on top of current `devel`, my test controls now look like this:

image

They used to look like this:

image

Control configuration in `config.yaml` is this:

``` yaml
controls:
  - name: Fan
    layout: horizontal
    children:
    - name: Enable Fan
      command: M106 S%(speed)s
      input:
      - name: Speed (0-255)
        parameter: speed
        default: 255
        slider:
          min: 0
          max: 255
    - name: Disable Fan
      command: M107
  - name: Example for multiple commands
    children:
    - name: Move X (static)
      confirm: You are about to move the X axis right by 10mm with 3000mm/s.
      commands:
      - G91
      - G1 X10 F3000
      - G90
    - name: Move X (parametric)
      commands:
      - G91
      - G1 X%(distance)s F%(speed)s
      - G90
      input:
      - default: 10
        name: Distance
        parameter: distance
      - default: 3000
        name: Speed
        parameter: speed
  - name: Reporting
    children:
    - name: Get Position
      command: M114
      regex: "X:([0-9.]+) Y:([0-9.]+) Z:([0-9.]+) E:([0-9.]+)"
      template: "Position: X={0}, Y={1}, Z={2}, E={3}"
  - name: Fun stuff
    children:
    - name: Dance
      script: custom/dance.gco
      input:
      - name: Go arounds
        parameter: repetitions
        slider:
          max: 10
          min: 1
          step: 1
```

Ideas? I made sure to rebuild the css just to be on the safe side and of course cleared my cache (multiple times actually).

**Comment by Salandora** [comment]
I'll gonna check that when home. Guess it might have something to do with a div container I set around each input. Of course I'll fix it.

**Comment by Salandora** [comment]
As I see it is possible to have a button and output at once. This throws me back a bit.

**Comment by Salandora** [comment]
Could you provide me with the dance.gco so I can implement the script part too?

**Comment by foosel** [comment]
Merged final version:

image

Generated from this `config.yaml` snippet and a plugin's additional controls:

``` yaml
controls:
- children:
  - command: M106 S%(speed)s
    input:
    - default: 255
      name: Speed (0-255)
      parameter: speed
      slider:
        max: 255
        min: 0
    name: Enable Fan
  - command: M107
    name: Disable Fan
  layout: horizontal
  name: Fan
- children:
  - commands:
    - G91
    - G1 X10 F3000
    - G90
    confirm: You are about to move the X axis right by 10mm with 3000mm/s.
    name: Move X (static)
  - commands:
    - G91
    - G1 X%(distance)s F%(speed)s
    - G90
    input:
    - default: 10
      name: Distance
      parameter: distance
    - default: 3000
      name: Speed
      parameter: speed
    name: Move X (parametric)
  collapsed: true
  name: Example for multiple commands
- children:
  - command: M114
    defaultValue: n/a
    name: Get Position
    regex: X:([0-9.]+) Y:([0-9.]+) Z:([0-9.]+) E:([0-9.]+)
    template: 'Position: X={0}, Y={1}, Z={2}, E={3}'
  name: Reporting
- children:
  - input:
    - name: Go arounds
      parameter: repetitions
      slider:
        max: 10
        min: 1
        step: 1
    name: Dance
    script: custom/dance.gco
  name: Fun stuff
```

**Pull request merged**
