### PR TITLE
Update FontAwesome to 4.7

### PR DESCRIPTION
**Pull request by Depaulicious**
Okay, so as I promised in #1842 I updated FontAwesome in OctoPrint.
This PR includes two commits: one that updates the fonts and the main CSS (with some patches to make it continue to work with old `icon-` classes) and one that updates the templates in order to use the new `fa-` classes.

Note that `octoprint.css` looks rewritten because I regenerated `octoprint.less`, I had to add a class.

### CODE REVIEW

**Comment by foosel** [comment]
Currently fighting with 1.3.3 / some fixes, will take a look and merge (or even backport to `maintenance`) once I've won ;)

**Comment by foosel** [comment]
@Depaulicious Instead of completely replacing the old Font Awesome with the new version, could you change this so that the old version is still available and the new one added concurrently? I know you patched the `css` to allow the `icon-` prefixes to still work, but I'm worried that we nevertheless might introduce regressions that way, plus it will make updating to newer versions of "NewFontAwesome" more tricky since we'd need to manually merge with your compatibility layer everytime. And as discussed in #1842 it might in general be less disruptive to do a soft-rollout.

**Comment by BillyBlaze** [comment]
Is it perhaps a good idea if we would put this in a jinja2 helper?

e.g. something like:
```{{ 'circle' | icon }}``` that would generate into ```<i class="fa fa-circle"></i>```

**Comment by Depaulicious** [comment]
@foosel I think so, as long as CSS allows to rename fonts so I can use the new one with `fa-` and the old one with `icon-`. Is it okay for you if I `rebase -i` the branch and delete the CSS commit, then add the new one without stacking up changes?

@BillyBlaze I don't think so. While many icons are just `fa fa-something`, some include other classes to implement different functionality (stack icons, spinning icons, etc). So that would lead to ugly workarounds IMO.

**Comment by foosel** [comment]
@Depaulicious you could use sub folders for the two versions to keep css and font files disjunct, the css already uses relative paths if I'm not mistaken? I'd be fine with moving the font-awesome stuff into its own folders (e.g. `assets/vendor/fontawesome3.2.1` and `..../fontawesome4`) if that would help things along.

Rebasing is totally fine!

@BillyBlaze What @Depaulicious said, I fear that while that would help in a lot of "normal" cases, there are a lot of locations even within stock OctoPrint where I used some spinning and such that would then not be captured (or the custom filter would become too complicated). I mean, yes, it would allow easier switching to newer versions if future FA installments change the syntax yet again, but I fear the cost for that would be too high to make it really a 100% solution.

**Comment by Depaulicious** [comment]
Alright. I'll rebase then and try to do that. I'll also rebase on top of the new `devel` changes.

**Comment by foosel** [comment]
I'll probably try to get it into 1.3.4 (1.4.0/`devel` is still far off), so if you go against `maintenance` instead of `devel`, that might be even better.

**Comment by Depaulicious** [comment]
Okay, I'll try. Hopefully it won't conflict against _everything_. I think I have to resubmit the PR for github to allow merging, though, unless you're going to merge it manually.

**Comment by foosel** [comment]
Just saw that you changed the base branch, so apparently a re-submit isn't necessary (anymore)? Conflicts should hopefully be minimal, there haven't been that many changes to the UI stuff so far on `devel` as far as I can remember.

**Comment by Depaulicious** [comment]
Yes I changed it. I just finished cherry-picking my commit on top of `maintenance` and I'm currently adding the two FontAwesome versions.

**Comment by Depaulicious** [comment]
I'm kind of worried that keeping the directory structure for css won't be a good thing when OctoPrint squashes all the stylesheets together. I think I'll keep it for the fonts only.

**Comment by foosel** [comment]
Well, it could be done with a CSS rewrite routine in the webassets setup, but yes, for now let's not make it overly convoluted :D

**Comment by Depaulicious** [comment]
Okay this should do it.

**Comment by foosel** [comment]
:+1:

**Pull request merged**
