### PR TITLE
Added ambientTemp to virtual printer

### PR DESCRIPTION
**Pull request by mcecchi**
#### Tested thoroughly, and I think it works.
----

### CODE REVIEW

**Comment by foosel** [comment]
Sorry, but I can't stop laughing right now. I added *exactly* the same kind of functionality yesterday (just with a configurable ambient value and a debug command to also modify it during run time). See fbcbb3f5f792a4104fdc9b33991448d10a9b5b1d

I can't believe this coincidence XD

My version exists on `maintenance` and once I do the next merge to `devel` it will be also on there. I guess it should also fit your use case - is that correct? :) Otherwise we can work something out.

**Comment by mcecchi** [comment]
Unbelievable Gina!!! XD

So, that said, your solution is surely better than mine.

We’ll talk on next PR!

**Comment by foosel** [comment]
Alright, closing this then. Really... what a coincidence!

**Comment by mcecchi** [comment]
Hi Gina,

I expected this feature at least in 1.3.5... what's happened?

Tnx

**Comment by foosel** [comment]
Wrong expectation on your part ;) 1.3.5 was already in feature freeze mode for around a month when our exchange above happened (and then final stable release got delayed severely thanks to the Flu of Doom 2017 edition). The commit will be part of 1.3.6.

**Comment by mcecchi** [comment]
Grazie!!!

We'll talk to you soon! ;-)

**Pull request closed without merging**
