### PR TITLE
Fix sorting of templates

### PR DESCRIPTION
**Pull request by Salandora**
I noticed that no sorting is happening no matter what "key" I gave for sorting.
So I investigated the situation and found that there was a hard coded check for key == name, 
but nothing for key != name

### CODE REVIEW

**Comment by Salandora** [comment]
I wasn't aware that this could be something else then a tuple. Otherwise I would have made a check like you did just with less lambda xD.

Shall I copy the code or do you commit it yourself?
As always I don't care ;-)

**Comment by foosel** [comment]
Haven't tested it, only write it down (vacation ;)). Also currently having issues with my wrist, so if you could test it a bit I'd be grateful :)

**Comment by Salandora** [comment]
Alright I test it.

**Comment by Salandora** [comment]
Re opening PR with new Branch for better History

**Pull request closed without merging**
