### PR TITLE
New feature: Added feature for printer movement control by keyboard

### PR DESCRIPTION
**Pull request by nEuDy**
-added a new field in the control-section, for controlling the movement of
the printer by keypresses.
To control you printer by keypress, you have to connect to printer first.
Then click into the textfield to activate it. Now you can press the arrow
keys, to move the printhead in the X- and Y-directions, press the W or S
key for Z-direction or the number keys 1, 2, 3 or 4 for choose the
distance (0.1mm, 1mm....)

### CODE REVIEW

**Comment by foosel** [comment]
Thanks for this, this is a neat feature! I changed the implementation a bit, the controls are now activated when you move the mouse over the camera picture, a little overlay is embedded to indicate this and this also includes the key reference. I also added homing of X/Y and Z to the available controls and added PageUp/PageDown for Z and the numblock numbers for the step size.

https://www.youtube.com/watch?v=2WsvvLRf1qc

**Comment by nEuDy** [comment]
Wow, thank you :-)
The last months i hadn´t much time to have a look at your cool project. And now i got, you´ve added my idea :-)
I´m happy to see you liked my idea and use it!
Thanks

BTW: At your G+ Site you wrote at the related post for this feature, what do do if anyone has no webcam steam:
Whats about a toggle button near the control section, for switching between "Default Website Click Control" (i know it´s a bad called name :-P) and the "Key Control"? For example, if it´s switched to Key Control, then you can suppress the access to all other function by an overlay page, like the "Server Offline Page". So it´s suppressed, that someone do a misstake during clicking the website or will control the printer during a print with the keys. Thanks again :-)

**Comment by chewy21** [comment]
hy, first of all nice feature !!
but i have a question that doesn't diserve an issue....
i'm looking to have some custom controls on my panel but went i read my config.yaml the "controls:" section is not in it. And if i try to add it the server crash after the reboot ... 
if someone have an answer for me ... 

Thanks !

**Comment by markwal** [comment]
@chewy21: huh? That's not related to this PR. Have you tried posting to the octoprint google+ community?

**Comment by chewy21** [comment]
huuum nop, sorry
i'll try on G+ community !

bye and thanks for the time

**Pull request merged**
