### PR TITLE
Fix for File not able to delete after Serial Error

### PR DESCRIPTION
**Pull request by Salandora**
As said in IRC, if you print and a Serial error occurs you were not able to delete the file.

This small fix takes care of it, every PrintingGcodeFileInformation subscribes to the FILE_DESELECTED event, and closes the _handle if still open.

### CODE REVIEW

**Comment by foosel** [comment]
Hm... I don't like using the event subsystem for that to be honest. First of all it adds a rather long roundtrip (through the event subsystem) for something that could be handled better by ``comm.py`` itself (which has the reference to the `PrintingGcodeFileInformation` anyways), secondly I'm not sure if that covers all bases (e.g. if the `_monitor` loop runs into an exception the deselected event will not be sent as far as I can see right now).

I'd suggest to instead close it if it's open when switching to the `ERROR` state. That should cover all bases from what I'm seeing.

**Comment by Salandora** [comment]
So you mean when _changState(ERROR/CLosed_WITH_ERROR) is called it shall close the handle there?

**Comment by Salandora** [comment]
Alright I'll change it :-)

**Comment by foosel** [comment]
As talked about on IRC, quickly moved to comm.py and turned into one single commit as seen above.

**Pull request closed without merging**
