### PR TITLE
Trust basic authentication headers for user login.

### PR DESCRIPTION
**Pull request by bzed**
This is my suggestion on how to handle basic authentication for users
mananaged by OctoPrint's UserManager.

In my opinion OctoPrint should not be doing Basic Authentication on its
own. The commen case is that it runs on some slow hardware which its not
able to handle stupid bots trying out thousands of passwords in short
time. Also you want to protect it as much as possible from the outside
to ensure that the basd internet can't break your 72h print after 71
hours by brute-forcing passwords.

So I'm introducing an
  accessControl: trustBasicAuthentication
config option. If enabled, it will take the user name from the
Authorization header, check if the user exists and is enabled - and if
so, just login the user.

OctoPrint works well for me with my haproxy basic auth setup - with disabled autologin.
Although I'm not sure if the settings should not me merged somehow into the autologin settings as it is something similar.

Also anonymous logins for a disabled user manager is not implemented. I'm not exactly sure if it is necessary at all, but it should not be hard to add.

Thank you for your interest into contributing to OctoPrint, it's
highly appreciated!

Please make sure you have read the "guidelines for contributing" as
linked just above this form, there's a section on Pull Requests in there
as well that contains important information.

As a summary, please make sure you have ticked all points on this
checklist:

  * [X] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [X] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [X] Your PR targets OctoPrint's devel branch, or maintenance if it's
    a bug fix for an issue present in the current stable version (no PRs
    against master or anything else)
  * [X] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature
  * [X] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase your PR if necessary!
  * [X] Your changes follow the existing coding style
  * [X] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [X] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [X] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

Feel free to delete all this help text, then describe
your PR further. You may use the template provided below to do that.
The more details the better!

----

#### What does this PR do and why is it necessary?
Using basic auth together with the normal login has some issues (#2297 for example), lets trust basic auth and avoid the double login part!

#### How was it tested? How can it be tested by the reviewer?
Setup a haproxy with basic auth as documented in the wiki and add a user with the same name in Octoprint and in the haproxy config.

#### Any background context you want to provide?
none :)

#### Screenshots (if appropriate)
not necessary.

#### Further notes
Comments welcome ;)

### CODE REVIEW

**Comment by foosel** [comment]
👍 I think this should be included in 1.3.7 already, would you mind changing that PR over to `maintenance`?

**Comment by bzed** [comment]
I'll figure out what the difference was for maintenance. I *think* https://github.com/bzed/OctoPrint/commits/basic_auth_autologin worked okay-ish, but I'm not sure about the api login anymore. Will figure it out, but due to the principal stuff it needs a bit different code.

**Comment by bzed** [comment]
@foosel https://github.com/bzed/OctoPrint/commits/basic_auth_autologin is rebased on the maintenance branch. basically the same code +- the merge conflict. Works for me, not really well tested, though.

**Comment by foosel** [comment]
I've created #2405 based on that. If you could give that a test spin against your setup that would help a lot. I tested it against a local setup, but just in case... ;) 

Heads-up: I added an option that is enabled by default to not only fetch the user name from the header but also check if the password matches. This can be disabled however, just set `accessControl.checkBasicAuthenticationPassword` to false in `config.yaml`. Reason: I wanted to make it a bit more tricky for users to shoot themselves in the foot by having this enabled but their instance still also accessible without basic auth in front of it.

Closing this one since it's superseded by #2405.

**Pull request closed without merging**
