### PR TITLE
[Request] [PR] Added favicon.ico support to OctoPrint

### PR DESCRIPTION
**Pull request by OutsourcedGuru**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch, or maintenance if it's
    a bug fix for an issue present in the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR 
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
I noticed that the `octoprint.log` includes 404 errors for a popular file which browsers always seem to want: `favicon.ico`. The icon is also seen in the browser's location field in many cases, is included on smartphone screens when you bookmark it, etc.

#### How was it tested? How can it be tested by the reviewer?
`curl -v -o ~/Desktop/downloaded_icon.ico http://localhost:5000/favicon.ico`
The MIME type should be:
```
< Content-Type: image/x-icon
```

`open ~/Desktop/downloaded_icon.ico`

Alternatively, open in browser and look for the icon to appear in the URL bar.

#### What are the relevant tickets if any?
N/A

#### Screenshots (if appropriate)
favicon.ico

#### Further notes

### CODE REVIEW

**Comment by tedder** [comment]
I think more needs to be done, see:
f69718b060237970e2bedfc51aa33131673018e7
1ec61a9fe6fbfa2fff71ad056d3623715792d9e4

The favicon already exists (mostly as a svg); this should be a redirect or *something* .. perhaps even swallowing the 404 without emitting an error, idk. Have you seen browsers that aren't displaying a favico?

**Comment by foosel** [comment]
As @tedder said, there's already an SVG favicon set via `meta` headers that even gets adjusted in color to the selected instance color. But I also agree that the logged 404s can be annoying (I haven't seen any in my own logs that I can remember though, but I've seen them in submitted logs). 

So in general I'm fine with adding a static `ico` one as well, though I'd rather have it as static file on disk instead of encoded (makes changing things so tricky ;)). But only if that doesn't interfere with the existing SVG favicon support, as in, the browser suddenly starts preferring the static one. Could you verify that?

Also please squash your commits and also do this PR against `maintenance` - this is an improvement of existing functionality or even a bugfix and should go into 1.3.11, not a giant new feature that needs time to ripe :)

**Comment by OutsourcedGuru** [comment]
This would be Safari 12.0.2 which for whatever reasons didn't pull the earlier attempt.

Do you want the ico somewhere special (as a discreet file)?

**Comment by OutsourcedGuru** [comment]
> "this should be a redirect or _something_"

@tedder Can you elaborate more on what you had in mind here?

What's clear is 1) go from encoded to file... and then I'm not sure if you want me to interact with something in the meta tags or what.

**Comment by tedder** [comment]
what I mean is if you put a favico up, it won't match the "themed" favico in the code. You'd have to apply the theme (color) over the top of it. That's what Gina is saying too:
> But only if that doesn't interfere with the existing SVG favicon support, as in, the browser suddenly starts preferring the static one.

So what I'm saying, as an option, is to put an endpoint at favico and return a 404. That would keep it from logging an error, and would keep the static favico from serving instead of the javascripty version in f69718b060237970e2bedfc51aa33131673018e7.

I just pulled up Safari ad it put the favico in the bookmark, so it's there. It wasn't themed by the JS though.

**Comment by tedder** [comment]
from a source I've used before:
> Is it true that favicons should be in the site root? No, that's only if you don't explicitly specify the browser/device-specific <link> tags with a favicon path. See https://en.wikipedia.org/wiki/Favicon.ico. [...] If you don't have favicon.ico in the root consider adding one, or returning a HTTP 204 instead.

https://github.com/audreyr/favicon-cheat-sheet

**Comment by OutsourcedGuru** [comment]
I've reviewed the HTML source and it does appear to have a header reference to `/static/img/tentacle-32x32.png`.

Maybe the earlier 404 was related to startup performance on something. I've seen in a far number of times in the last year and I've not really thought much about it. I looked through the repository for a `favicon.ico`, didn't see it and wrongly assumed that it wasn't included.

I'd like to just close this, if that's alright.

**Pull request closed without merging**
