### PR TITLE
WIP: Update to Bootstrap 3.3.1

### PR DESCRIPTION
**Pull request by skalnik**
:warning: This PR is currently a Work in Progress :warning:

I've been looking at getting OctoPrint displayed nicely on smaller screens. To make this a bit easier I started moving from Bootstrap 2 to the latest version of Bootstrap 3. ~~After initially messing with it, it doesn't seem to break much of anything~~ JK, lots of stuff breaks :crying_cat_face: 

Please let me know if things seem off or if anyone finds something broken.

### To do:

* [x] Replace the actual css :art:
* [x] Replace the less source :computer: 
* [ ] [Migrate major class name changes](http://getbootstrap.com/migration#classes) :bird: 
* [ ] Investigate & update any [Bootstrap 3 removals](http://getbootstrap.com/migration#dropped) :x:
* [ ] Investigate & update the bootstrap plugins (slider & modal) :electric_plug:
* [x] Write a to do list :white_check_mark:

#### Migrate major class name changes:

* [x] `.row-fluid`:point_right:`.row`
* [x] `.span*`:point_right:`.col-md-*`
* [x] `.offset*`:point_right:`.col-md-offset-*`
* [ ] `.brand`:point_right:`.navbar-brand`
* [ ] `.navbar .nav`:point_right:`.navbar-nav`
* [ ] `.nav-collapse`:point_right:`.navbar-collapse`
* [ ] `.nav-toggle`:point_right:`.navbar-toggle`
* [ ] `.btn-navbar`:point_right:`.navbar-btn`
* [ ] `.hero-unit`:point_right:`.jumbotron`
* [ ] `.icon-*`:point_right:`.glyphicon .glyphicon-*`
* [ ] `.btn`:point_right:`.btn .btn-default`
* [ ] `.btn-mini`:point_right:`.btn-xs`
* [ ] `.btn-small`:point_right:`.btn-sm`
* [ ] `.btn-large`:point_right:`.btn-lg`
* [ ] `.alert-error`:point_right:`.alert-danger`
* [ ] `.visible-phone`:point_right:`.visible-xs`
* [ ] `.visible-tablet`:point_right:`.visible-sm`
* [ ] `.visible-desktop`:point_right:`Split into .visible-md .visible-lg`
* [ ] `.hidden-phone`:point_right:`.hidden-xs`
* [ ] `.hidden-tablet`:point_right:`.hidden-sm`
* [ ] `.hidden-desktop`:point_right:`Split into .hidden-md .hidden-lg`
* [ ] `.input-block-level`:point_right:`.form-control`
* [ ] `.control-group`:point_right:`.form-group`
* [ ] `.control-group.warning .control-group.error
* [ ] .control-group.success`:point_right:`.form-group.has-*`
* [ ] `.checkbox.inline .radio.inline`:point_right:`.checkbox-inline .radio-inline`
* [ ] `.input-prepend .input-append`:point_right:`.input-group`
* [ ] `.add-on`:point_right:`.input-group-addon`
* [ ] `.img-polaroid`:point_right:`.img-thumbnail`
* [ ] `ul.unstyled`:point_right:`.list-unstyled`
* [ ] `ul.inline`:point_right:`.list-inline`
* [ ] `.muted`:point_right:`.text-muted`
* [ ] `.label`:point_right:`.label .label-default`
* [ ] `.label-important`:point_right:`.label-danger`
* [ ] `.text-error`:point_right:`.text-danger`
* [ ] `.table .error`:point_right:`.table .danger`
* [ ] `.bar`:point_right:`.progress-bar`
* [ ] `.bar-*`:point_right:`.progress-bar-*`
* [ ] `.accordion`:point_right:`.panel-group`
* [ ] `.accordion-group`:point_right:`.panel .panel-default`
* [ ] `.accordion-heading`:point_right:`.panel-heading`
* [ ] `.accordion-body`:point_right:`.panel-collapse`
* [ ] `.accordion-inner`:point_right:`.panel-body`

### CODE REVIEW

**Comment by foosel** [comment]
Wow, awesome! I tried my hand at this a while back but a lot of stuff broke, so I postponed that. :+1:

**Comment by skalnik** [comment]
> Wow, awesome! I tried my hand at this a while back but a lot of stuff broke, so I postponed that.

Yeah it looks it required a rebuild to reload assets, so a lot of stuff did break! However I'll see what I can do :wrench:

**Comment by punkkeks** [comment]
Any progress so far?

**Comment by skalnik** [comment]
No I've let this go rather stale :(

**Comment by markwal** [comment]
@punkkeks While you're waiting for bootstrap 3 (or working on it, whatever the case may be) if responsive is what you're after you could try my [ScreenSquish](https://github.com/markwal/OctoPrint-ScreenSquish) plugin.

**Comment by jneilliii** [comment]
@markwal curious if you've tried my stl viewer with screen squish? I know the Javascript base I integrated has touch screen support.

**Comment by markwal** [comment]
Kinda. The touch bit works fine. The phone has a little trouble rendering (slower than the desktop) and it's not centered, but other than that, it works. :-)

image

**Comment by sdaitzman** [comment]
Bootstrap 4 is now out, so perhaps that should be the target instead. Currently it's in early alpha stages.

**Pull request closed without merging**
