### PR TITLE
Debian Packaging

### PR DESCRIPTION
**Pull request by croadfeldt**
I wanted to have a Debian package for use with my replicape/redeem packaging efforts. Created a debian wheezy package on a BeagleBone Black. But this should work on any Wheezy based install. This process pulls in packages from Wheezy, Wheezy-backports, jessie and one PIP install. All are deb packages from official debian sources, minus the one PIP install.

README.md has been updated with instructions. I assume changes will happen to make this process more version independent, but at least for now, this current process results in a fully functional deb package using systemctl and running as non-root user octo.

### CODE REVIEW

**Comment by croadfeldt** [comment]
One change to Octoprint sources, I updated requirements.txt to allow for some newer versions of python modules vs hardcoded versions as defined in requirements.txt. So far all is well and octoprint works exactly as expected. Otherwise all changes are on new files added for deb packaging.

**Comment by croadfeldt** [comment]
If you're curious why I PR'd against master vs devel, it's because I wanted a debian package of the stable branch. Should be easy enough to move this to devel and fix the module versioning to be more resilient. i.e.; not hardcoded versions. :)

**Comment by croadfeldt** [comment]
Sorry for the lengthy commit list. I'm a stickler for making changes one at a time, committing them and then testing based on git pull on a separate system. The packaging process is not as clean as I would like. It works and produces a valid package, but it's not %100 debianized yet. I was trying to make it so and forget I had a PR that would show all the changes. Will branch and work there instead. This PR is still valid and does produce a deb package for wheezy. Jessie might work if you skip the wheezy-instructions step, but I have not tested that yet.

**Comment by foosel** [comment]
No worries. Will take a look when I'm back at work (next week), currently
on vacation.

**Comment by foosel** [comment]
A possibly stupid question, but wouldn't it make more sense to maintain this in another repository, `wget`ting the current source tarball prior to building the `deb`? We could host that under the github OctoPrint organization and I could add you as contributor, giving you write access to that debian-package repo. 

There might be a problem with the updated requirements for `devel`, I know that there's at least one breaking change caused by updating Flask to 0.10.

**Comment by croadfeldt** [comment]
Not a stupid question at all. This effort was me getting it up and running and sharing if you wanted to pull it in. Keeing the packaging separate in another repo as you stated is how it should be. Hence my apprehension earlier. Do you want to create repo and I can fork, then PR it when it's ready or would you prefer I just open a new repo for it?

As for the compatibility for devel, minor issue. :) That can be addressed easy enough with separate packaging tags for each release in the packaging repo.

**Comment by foosel** [comment]
That depends. If you want I can create a repo under the [OctoPrint organization](https://github.com/OctoPrint) and give you full access to that. Or alternatively you create it under your own account. I'll leave that up to you :)

**Comment by croadfeldt** [comment]
@foosel It doesn't make sense for me to own the packing repo for Octoprint, so if you want to open up the repo, I will move everything over to it. :)

@eliasbakken Where are you seeing the package for CuraEngine? I did a cursory look and didn't see it in the git repo. I can give that some deb love too if needed.

**Comment by foosel** [comment]
> It doesn't make sense for me to own the packing repo for Octoprint

Why not? You could keep maintaining it (because I certainly have no idea of what to do there), your name would be properly be associated with it (fame and fortune, haha!), you'd keep control. I mean, I don't have a problem with the other option either, although I'd find it a bit sad if it then might just end up unmaintained.

**Comment by eliasbakken** [comment]
@croadfeldt, Cura has a (somewhat awkward) way of building .deb packages
built in to the Makefile. It also includes CuraEngine in the package so
that is taken care of. The .deb is in my armhf feed.

@foosel, I don't think you would need to do anything other than to host the
code and merge changes. I can host the feed for the armhf packages for
Octoprint if there are no better place to put them, but I have no interest
or ability to host for any other architectures. Actually, it might be a
nice program for the upstream Debian feed, so someone should try that :)


Kind regards,
-Elias

2015-04-22 14:57 GMT+02:00 Gina Häußge <notifications@github.com>:

**Comment by croadfeldt** [comment]
@eliasbakken I chose that method to make it incredibly easy for anyone to kick off a package creation task. This is handy if you want to be able keep the packaging part of the source code and is really just a wrapper for the packaging process scripts. It's the same thing that I did for your code that you have in your debian repo now. It can be really easily split out and incorporated with git. Which is what I will do here.

@foosel My thoughts were to keep the packaging repo in the same "house" as it were to Octoprint. I have no issues spinning up a repo for it and will do so. I'm going to look into having packages auto generated, perhaps daily, on the fly, when tags are applied, etc... I don't mind being the maintainer and use Octoprint daily, so I don't force it being abandoned.

**Comment by croadfeldt** [comment]
Ok, I'm going to close this PR. Open up a new repo for the packaging and get rolling on that.

@eliasbakken Since most of your code is python based as well, this same approach can be taken with your packages as well.

**Comment by eliasbakken** [comment]
@croadfeld yes, please do! Would be great to have autobuilt packages fresh
from the repo:)
22. apr. 2015 17:01 skrev "croadfeldt" <notifications@github.com>:

**Pull request closed without merging**
