### PR TITLE
spellfix 'sdReleativePath'

### PR DESCRIPTION
**Pull request by tedder**
It's only misspelled in the docs, it is correct in the code.

Hoping the bot won't complain about an empty PR.

  * [ ] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch, or maintenance if it's
    a bug fix for an issue present in the current stable version (no PRs
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR 
    if necessary!
  * [ ] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

### CODE REVIEW

**Comment by foosel** [comment]
Since this constitutes a documentation fix (which is somewhat similar to a bug fix really), could you open that against `maintenance`? I could also cherry-pick it if not. Just can't simply switch the target branch up there because that will rebase *everything* on `devel` against `maintenance` and that's definitely not what we want here ^^

**Comment by tedder** [comment]
Done. Dunno if you want this one closed or what. I still don't understand `devel` vs `maintenance` vs `master` for new development :)

**Comment by foosel** [comment]
To quote ["What do the branches mean?"](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md#what-do-the-branches-mean):

>  * `master`: The master branch always contains the current stable release. It
>    is *only* updated on new releases. Will have a version number following
>    the scheme `<x>.<y>.<z>` (e.g. `1.2.9`) or - if it's absolutely necessary to
>    add a commit after release to this branch - `<x>.<y>.<z>.post<commits since x.y.z>`
>    (e.g. `1.2.9.post1`).
>  * `maintenance`: Improvements and fixes of the current release that make up
>    the next release go here. More or less continuously updated. You can consider
>    this a preview of the next release version. It should be very stable at all
>    times. Anything you spot in here helps tremendously with getting a rock solid
>    next stable release, so if you want to help out development, running the
>    `maintenance` branch and reporting back anything you find is a very good way
>    to do that. Will usually have a version number following the scheme
>    `<x>.<y>.<z+1>.dev<commits since increase of z>` for an OctoPrint version of `<x>.<y>.<z>`
>    (e.g. `1.2.10.dev12`).
>  * `devel`: Ongoing development of new features that will go into the next bigger
>    release (MINOR version number increases) will happen on this branch. Usually
>    kept stable, sometimes stuff can break though or lose backwards compatibility
>    temporarily. Can be considered the "bleeding edge". All PRs should target
>    *this* branch. Important improvements and fixes from PRs here are backported to
>    `maintenance` as needed. Will usually have a version number following the
>    scheme `<x>.<y+1>.0.dev<commits since increase of y>` for a current OctoPrint version
>    of `<x>.<y>.<z>` (e.g. `1.3.0.dev123`).

So - no new development at all on `master`. `maintenance` gets fixes, improvements and minor features. `devel` gets the big stuff that takes a long while to get working.

**Comment by foosel** [comment]
Also closing this in favor of #2827 :)

**Comment by tedder** [comment]
oh snap, you FAQed me. I thought I should focus on devel, I was confused why you wanted it on maintenance.

**Comment by foosel** [comment]
It's always depends on the contents and hence nature of the PR. The Python 3 stuff is an ongoing larger change, so `devel`. But doc fixes, bug fixes, stuff like "look, there was a typo in the UI here" and similar things are prime candidates for `maintenance` :)

**Pull request closed without merging**
